# Generated by Django 3.0.5 on 2020-04-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country_region_name',
            field=models.CharField(max_length=100, verbose_name='国または地域'),
        ),
    ]
