# Generated by Django 3.0.5 on 2020-04-26 23:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200426_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='total_cases',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='累計感染者数'),
        ),
    ]
